# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # "vagrant box add puppetlabs/centos-6.6-64-puppet" to add the vm image
  # to the list of images vagrant knows about. This will download the 
  # image from the vagrant catalog. (You may need a url if not in the
  # catalog)

  # front end web server

  config.vm.define "mmowgli" do |mmowgli|
    mmowgli.vm.box = "puppetlabs/centos-6.6-64-puppet"
    mmowgli.vm.hostname = "mmowgli"
    mmowgli.vm.network "private_network", ip:"10.1.100.2"
  end

  # database, zookeeper, JMS server

  config.vm.define "mmowgliServer" do |mmowgliServer|
    mmowgliServer.vm.box = "puppetlabs/centos-6.6-64-puppet"
    mmowgliServer.vm.hostname = "mmowgliServer"
    mmowgliServer.vm.network "private_network", ip:"10.1.100.3"
  end

  # one of N tomcat servers that can be loadbalanced across. 
  # Add the list of tomcat servers to the tomcats list in
  # hiera.

  config.vm.define "tomcat1" do |tomcat1|
    tomcat1.vm.box = "puppetlabs/centos-6.6-64-puppet"
    tomcat1.vm.hostname = "tomcat1"
    tomcat1.vm.network "private_network", ip:"10.1.100.4"
  end


  config.vm.define "tomcat2" do |tomcat2|
    tomcat2.vm.box = "puppetlabs/centos-6.6-64-puppet"
    tomcat2.vm.hostname = "tomcat2"
    tomcat2.vm.network "private_network", ip:"10.1.100.5"
  end

  # This installs some basic stuff so we can go on to provision
  # the rest with ansible or puppet.
   config.vm.provision "shell", inline: <<-SHELL
     
     # Ansible
     sudo yum install ansible
     
     # puppet and hiera config files

     cp /vagrant/puppetConfig/hiera.yaml /etc/puppet
     cp -R /vagrant/puppetConfig/hieradata /etc/puppet
     cp /vagrant/puppetConfig/puppet.conf /etc/puppet
    
     # baseline puppet modules. Note that you need to be connected to the internet
     # to retreive these.

#     /usr/bin/puppet module install puppetlabs/apache
#     /usr/bin/puppet module install puppetlabs/mysql
#     /usr/bin/puppet module install  puppetlabs/stdlib
#     /usr/bin/puppet module install thias/samba
#     /usr/bin/puppet module install puppetlabs/firewall

     #puppet apply --modulepath /etc/puppet/modules:/vagrant/manifests/modules /vagrant/manifests/site.pp
   SHELL
end
