package edu.nps.moves.mmowgli.modules.actionplans;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class _MediaPanel2 extends VerticalLayout
{
  protected HorizontalLayout titleHL;
  protected Label sp;
  protected Label indexLab;
  protected TextField title;
  protected TextArea caption;
  protected HorizontalLayout captionSavePan;
  protected Label lab;
  protected Button canButt;
  protected Button saveButt;
  protected Label lab2;

  public _MediaPanel2()
  {
    Design.read(this);
  }
}
