# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:/usr/java/default/bin
export PATH

export JAVA_HOME=/usr/java/default


