/*
* Copyright (c) 1995-2010 held by the author(s).  All rights reserved.
*  
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*  
*  * Redistributions of source code must retain the above copyright
*       notice, this list of conditions and the following disclaimer.
*  * Redistributions in binary form must reproduce the above copyright
*       notice, this list of conditions and the following disclaimer
*       in the documentation and/or other materials provided with the
*       distribution.
*  * Neither the names of the Naval Postgraduate School (NPS)
*       Modeling Virtual Environments and Simulation (MOVES) Institute
*       (http://www.nps.edu and http://www.MovesInstitute.org)
*       nor the names of its contributors may be used to endorse or
*       promote products derived from this software without specific
*       prior written permission.
*  
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
* CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
* ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*/
package edu.nps.moves.mmowgli.db.pii;
import javax.persistence.*;
import javax.persistence.Entity;

import org.hibernate.annotations.*;
import org.hibernate.annotations.Parameter;
import org.jasypt.hibernate4.type.EncryptedStringType;

/**
 * Vip.java
 * Created on May 8, 2012
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey, jmbailey@nps.edu
 * @version $Id$
 */

/** Used for jasypt encryption of fields */

@TypeDef(
      name="encryptedString", 
      typeClass=EncryptedStringType.class, 
      parameters={@Parameter(name="encryptorRegisteredName",
                             value="propertiesFileHibernateStringEncryptor")}
  )
  
@Entity
public class VipPii
{
  static public enum VipType {
    
    DOMAIN,EMAIL,EMAIL_BLACKLIST;
    
    public String description()
    {
      switch(this) {
        case DOMAIN: return "Domain";
        case EMAIL: return "Individual"; 
        case EMAIL_BLACKLIST: return "Individual blacklist";
      }
      throw new AssertionError("Unknown op: " + this);
    }
  };
  
  long   id;    /** Primary key, autogenerated */
  VipType   type;
  String entry;
  
  public VipPii()
  {
    
  }
  public VipPii(String entry, VipType typ)
  {
    setEntry(entry);
    setType(typ);
  }

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(nullable = false)
  public long getId()
  {
    return id;
  }

  public void setId(long id)
  {
    this.id = id;
  }

  @Type(type="encryptedString")
  public String getEntry()
  {
    return entry;
  }

  public void setEntry(String entry)
  {
    this.entry = entry;
  }

  @Basic
  public VipType getType()
  {
    return type;
  }

  public void setType(VipType type)
  {
    this.type = type;
  }
  
  public String toString()
  {
    return getEntry();
  }
}
