package edu.nps.moves.mmowgli.modules.administration;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class _MassMailJobPanel extends VerticalLayout
{
  protected Grid grid;
  protected HorizontalLayout buttsHL;
  protected Button scheduleButt;
  protected Button refreshButt;
  protected Button closeButt;
  protected GridLayout topGridLay;
  protected Label toLabel;
  protected Label subjectLabel;
  protected Label textLabel;

  public _MassMailJobPanel()
  {
    Design.read(this);
  }
}
