package edu.nps.moves.mmowgli.modules.administration;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class _MassMailEditorPanel extends VerticalLayout
{
  protected ComboBox existingCombo;
  protected Button selectExistingButt;
  protected Button newMessageButt;
  protected Label hintLab;
  protected VerticalLayout editorVL;
  protected OptionGroup recipientOptionGroup;
  protected TextField customTF;
  protected TextField subjectTF;
  protected RichTextArea richTextArea;
  protected HorizontalLayout buttHL;
  protected Button openMailJobButt;
  protected Button saveButt;
  protected Button cancelButt;

  public _MassMailEditorPanel()
  {
    Design.read(this);
  }
}
