package edu.nps.moves.mmowgli.modules.administration;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class _SetVideoPanel extends VerticalLayout
{
  protected OptionGroup typeOptionGroup;
  protected FormLayout html5FL;
  protected HorizontalLayout urlHL;
  protected TextField urlTF;
  protected Button urlTestButt;
  protected TextField posterTF;
  protected FormLayout youTubeFL;
  protected HorizontalLayout youtubeidHL;
  protected TextField youtubeIdTF;
  protected Button youTubeIdTestButt;
  protected FormLayout optionalFL;
  protected TextField altUrlTF;
  protected TextField titleTF;
  protected TextField descriptionTF;
  protected TextField widthTF;
  protected TextField heightTF;
  protected HorizontalLayout buttHL;
  protected Button cancelButt;
  protected Button saveButt;

  public _SetVideoPanel()
  {
    Design.read(this);
  }
}
